name: dinamik10_pos
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.0-171.0.dev

dependencies:
  flutter:
    sdk: flutter

#Core
  equatable: ^2.0.7
  get_it: ^8.0.3
#Network
  vexana: ^5.0.3


#State
  flutter_bloc: ^9.1.1

#Navigation
  auto_route: ^10.0.1

#Config
  #translation
  easy_localization: ^3.0.7+1 
  
#Utility
  logger: ^2.5.0
  bootstrap_icons: ^1.11.1
  google_fonts: ^6.2.1



  # Modules
  gen:
    path: module/gen
  common:
    path: module/common
  core:
    path: module/core
  widgets:
    path: module/widgets
 
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  auto_route_generator: ^10.0.1 
  

flutter:  
  uses-material-design: true
  
  assets:
    - assets/translations/